POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "a divina comedia",
  "author": "dante",
  "year": 1321,
  "genre": "poesia"
}

#GET http://localhost:3000/api/books/686c4d6a6336cb427d161f8b

# DELETE  http://localhost:3000/api/books/686c508b1870edf62a9cba79
# Content-Type: application/json
